'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const base='https://qa.example/dataprev-sessoes/ciclos/';let testPort;const http=require('http');const server=http.createServer((req,res)=>{let p=path.resolve(root,'..','.'+new URL(req.url,'http://localhost').pathname);if(p.endsWith('/ciclos'))p+='/index.html';try{let data=fs.readFileSync(p);res.writeHead(200);res.end(data);}catch{res.writeHead(404);res.end('not found');}});let offline=false,failOne=false,skipped=false,claimed=false;const listeners={},stores=new Map([['dataprev-sessoes-standalone-v37',new Map([['legacy','keep']])],['dataprev-ciclos-v0',new Map()]]),requests=[];
const normalize=r=>new URL(typeof r==='string'?r:(r.url||r.href),base).href;
const network=async req=>{const url=normalize(req);if(offline)throw Error('offline');const p=new URL(url).pathname.replace('/dataprev-sessoes/','/');if(failOne&&p.endsWith('model.js'))return new Response('failed',{status:404});let response=await fetch('http://127.0.0.1:'+testPort+p+new URL(url).search);requests.push({path:p,status:response.status});return response;};
const caches={async keys(){return [...stores.keys()]},async delete(k){return stores.delete(k)},async open(k){if(!stores.has(k))stores.set(k,new Map());const data=stores.get(k);return {async addAll(urls){let entries=await Promise.all(urls.map(async u=>{let r=await network(u);if(!r.ok)throw Error('precache failed');return [normalize(u),r];}));for(const [u,r]of entries)data.set(u,r);},async match(req,opts={}){let key=normalize(req);for(const [u,r]of data){if(opts.ignoreSearch?new URL(u).pathname===new URL(key).pathname:u===key)return r.clone();}},async put(req,r){data.set(normalize(req),r);}}}};
const self={location:{href:base+'service-worker.js',origin:new URL(base).origin},addEventListener:(n,fn)=>listeners[n]=fn,skipWaiting:()=>{skipped=true;return Promise.resolve()},clients:{claim:()=>{claimed=true;return Promise.resolve()}}};vm.runInNewContext(source,{self,caches,fetch:network,URL,Response,Promise,console});
async function lifecycle(name){let promise;listeners[name]({waitUntil:p=>promise=p});await promise;}
async function request(url,mode='cors'){let promise;listeners.fetch({request:{url:new URL(url,base).href,method:'GET',mode},respondWith:p=>promise=p});return await promise;}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));testPort=server.address().port;await lifecycle('install');assert.ok(skipped);assert.ok(requests.every(r=>r.status===200));await lifecycle('activate');assert.ok(claimed);assert.ok(stores.has('dataprev-sessoes-standalone-v37'));assert.ok(!stores.has('dataprev-ciclos-v0'));let ready,wait;listeners.message({data:{type:'CICLOS_OFFLINE_CHECK'},ports:[{postMessage:m=>ready=m}],waitUntil:p=>wait=p});await wait;assert.equal(ready.type,'CICLOS_OFFLINE_READY');offline=true;const html=await request('./?fresh=1','navigate');assert.equal(html.status,200);assert.ok((await html.text()).includes('DATAPREV · Ciclos'));const data=await request('content/bank.json?v=other');assert.equal((await data.json()).cycles[1].questions.length,70);for(const asset of ['styles.css?v=1.0.0','app.js?v=1.0.0','model.js?v=1.0.0','reader.html','icon.svg','icon-192.png','icon-512.png','manifest.webmanifest'])assert.equal((await request(asset)).status,200,asset);offline=false;failOne=true;skipped=false;await assert.rejects(()=>lifecycle('install'));assert.equal(skipped,false,'failed install must not skipWaiting');
const result={status:'PASS',httpRequests:requests.length,non200:requests.filter(x=>x.status!==200).length,checks:['clean install caches all assets','first and second cycles offline','navigation with query','versioned assets offline','offline ready requires complete cache','failed install does not activate','old cycles cache cleanup scoped','legacy cache preserved'],scope:'Service worker executed in isolated VM against actual local HTTP assets; offline network failure simulated. Not a physical iPhone install test.'};fs.writeFileSync(path.join(__dirname,'offline-result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));})().catch(err=>{console.error(err);process.exitCode=1;}).finally(()=>server.close());
