'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),bank=JSON.parse(read('content/bank.json')),M=require('../model.js');const results=[];
const test=(name,fn)=>{fn();results.push({name,status:'PASS'});};
const c=bank.cycles[0],q=c.questions[0];
test('first attempt immutable and independent of later selection',()=>{const s=M.fresh(),r=M.record(s,c,q);r.selected=q.answerId;r.confidence='alta';const first=M.clone(M.answer(q,r,'2026-09-09T00:00:00Z'));r.selected=q.options.find(o=>o.id!==q.answerId).id;r.helpOpenedAt='2026-09-09T00:01:00Z';M.answer(q,r);assert.deepEqual(r.firstAttempt,first);assert.equal(M.stats(c,s.cycles[c.id]).independent,1);});
test('complete two distinct cycles and weighted scoring',()=>{const s=M.fresh();for(const c of bank.cycles){for(const q of c.questions){const r=M.record(s,c,q);r.selected=q.answerId;r.confidence='media';if(q.number%2===0)r.helpOpenedAt='2026-09-09T01:00:00Z';M.answer(q,r);}const st=M.stats(c,s.cycles[c.id]);assert.equal(st.points,115);assert.equal(st.pending,0);assert.equal(st.correct,70);assert.equal(st.independent,35);assert.equal(st.assisted,35);}assert.equal(M.notebook(bank,s).length,140);});
test('all 700 option paths have exactly one correct classification per item',()=>{for(const c of bank.cycles)for(const q of c.questions){let right=0;for(const o of q.options){const r={selected:o.id,confidence:'alta',firstAttempt:null,helpOpenedAt:null};M.answer(q,r);if(M.correct(q,r.firstAttempt))right++;assert.equal(typeof o.feedback,'string');}assert.equal(right,1,q.id);}});
test('invalid and missing selections never create evidence',()=>{const r={selected:'bad',confidence:'alta',firstAttempt:null};assert.throws(()=>M.answer(q,r));assert.equal(r.firstAttempt,null);r.selected=q.answerId;r.confidence=null;assert.throws(()=>M.answer(q,r));assert.equal(r.firstAttempt,null);});
test('recovery preserves local first attempt, notes and imported evidence',()=>{let a=M.fresh(),b=M.fresh(),ar=M.record(a,c,q),br=M.record(b,c,q);ar.selected=q.answerId;ar.confidence='alta';ar.note='nota local';M.answer(q,ar,'2026-09-09T00:00:00Z');br.selected=q.options.find(o=>o.id!==q.answerId).id;br.confidence='baixa';br.note='nota de outro aparelho';M.answer(q,br,'2026-09-09T01:00:00Z');let out=M.merge(a,b,bank),r=out.cycles[c.id].records[q.id];assert.deepEqual(r.firstAttempt,ar.firstAttempt);assert.equal(r.importedAttempts.length,1);assert.equal(r.note,'nota local');assert.deepEqual(r.noteHistory,['nota de outro aparelho']);assert.equal(M.merge(out,b,bank).cycles[c.id].records[q.id].importedAttempts.length,1);});
test('checkpoint restores pending draft and current cycle on empty device',()=>{let s=M.fresh();const cy=bank.cycles[1],qq=cy.questions[23],r=M.record(s,cy,qq);s.lastCycle=cy.id;s.cycles[cy.id].position=23;r.selected=qq.options[2].id;r.confidence='baixa';r.note='não perder';r.helpOpenedAt='2026-09-09T00:00:00Z';const out=M.merge(M.fresh(),s,bank);assert.equal(out.lastCycle,cy.id);assert.equal(out.cycles[cy.id].position,23);assert.equal(out.cycles[cy.id].records[qq.id].selected,r.selected);assert.equal(out.cycles[cy.id].records[qq.id].note,r.note);assert.equal(out.cycles[cy.id].records[qq.id].firstAttempt,null);});
test('tampered checkpoint fails atomically, unknown IDs and completed-but-pending rejected',()=>{let s=M.fresh();M.record(s,c,q);let bad=M.clone(s);bad.cycles[c.id].records['unknown']=bad.cycles[c.id].records[q.id];assert.throws(()=>M.validate(bad,bank));bad=M.clone(s);bad.cycles[c.id].completedAt='2026-09-09T00:00:00Z';assert.throws(()=>M.validate(bad,bank));bad=M.clone(s);bad.cycles[c.id].records[q.id].selected='wrong option';assert.throws(()=>M.validate(bad,bank));assert.equal(s.cycles[c.id].completedAt,null);});
test('report excludes answers and rationale for pending questions',()=>{let s=M.fresh();M.record(s,c,q).note='pendente';let report=M.report(bank,s);assert.ok(!report.includes(q.explanation));assert.ok(!report.includes('Correta:'));assert.ok(report.includes('Pendente — gabarito não incluído.'));});
test('review date follows recorded attempt, not synthetic mastery',()=>{let s=M.fresh(),r=M.record(s,c,q);r.selected=q.options.find(o=>o.id!==q.answerId).id;r.confidence='alta';M.answer(q,r);r.reviews.push({id:'review-1',selected:q.answerId,confidence:'alta',assisted:false,at:'2026-09-09T12:00:00Z',reason:''});let entry=M.notebook(bank,s)[0];assert.equal(entry.due,'2026-09-12T12:00:00.000Z');assert.equal(M.stats(c,s.cycles[c.id]).correct,0);assert.ok(entry.reasons.includes('Erro na primeira resposta'));});
const delay=()=>new Promise(r=>setTimeout(r,15));
async function harness(seed,hash=''){
 const errors=[],downloads=[];let quota=false;const vc=new VirtualConsole();vc.on('jsdomError',er=>errors.push(er.message));let storage;
 const dom=new JSDOM(read('index.html'),{url:'https://qa.example/dataprev-sessoes/ciclos/'+hash,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.fetch=async u=>({ok:true,json:async()=>bank});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.Blob=Blob;w.URL.createObjectURL=b=>{downloads.push(b);return 'blob:qa';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};const set=w.Storage.prototype.setItem;w.Storage.prototype.setItem=function(k,v){if(quota)throw Error('quota');return set.call(this,k,v);};w.localStorage.setItem('dataprev_sessoes_states_v2','OFFICIAL-SENTINEL');w.localStorage.setItem('dataprev_sessoes_sync_queue_v2','QUEUE-SENTINEL');if(seed)w.localStorage.setItem(M.KEY,typeof seed==='string'?seed:JSON.stringify(seed));}});
 dom.window.eval(read('model.js'));dom.window.eval(read('app.js'));await delay();let w=dom.window,d=w.document;return {dom,w,d,errors,downloads,quota:v=>quota=v,click(sel){let el=d.querySelector(sel);assert.ok(el,sel);assert.ok(!el.disabled,sel+' enabled');el.click();return el;},input(sel,value){let el=d.querySelector(sel);assert.ok(el,sel);el.value=value;el.dispatchEvent(new w.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));},confidence(value='alta'){const el=d.querySelector(`input[name=confidence][value=${value}]`);el.checked=true;el.dispatchEvent(new w.Event('change',{bubbles:true}));},state(){return JSON.parse(w.localStorage.getItem(M.KEY));},close(){dom.window.close();}};
}
(async()=>{
 let h=await harness();test('clean boot no legacy mutation or invented progress',()=>{assert.equal(h.w.localStorage.getItem(M.KEY),null);assert.equal(h.w.localStorage.getItem('dataprev_sessoes_states_v2'),'OFFICIAL-SENTINEL');assert.ok(h.d.body.textContent.includes('Uma questão.'));assert.equal(h.errors.length,0);});
 h.click('[data-action=start]');test('question first, no premature feedback',()=>{assert.equal(h.d.querySelectorAll('.option').length,5);assert.equal(h.d.querySelectorAll('.option.correct,.option.wrong').length,0);assert.equal(h.d.querySelector('#feedback'),null);assert.equal(h.d.querySelector('#learning').open,false);assert.equal(h.d.querySelector('[data-action=grade]').disabled,true);});
 h.input('#note','Minha nota <script>não executar</script>');h.input('#reason','Pensei no limite da inferência.');h.click(`[data-option="${q.answerId}"]`);h.confidence();const draft=h.state();h.close();h=await harness(draft,'#study/ciclo-01/0');test('reload restores note and pending choice',()=>{assert.equal(h.d.querySelector('#note').value,'Minha nota <script>não executar</script>');assert.equal(h.d.querySelector('.option[aria-checked=true]').dataset.option,q.answerId);assert.equal(h.d.querySelector('#feedback'),null);});
 h.click('[data-action=grade]');const first=h.state().cycles[c.id].records[q.id].firstAttempt;test('correction and immutable first response',()=>{assert.ok(h.d.querySelector('#feedback').textContent.includes(q.explanation));assert.equal(first.assisted,false);assert.equal(h.d.querySelectorAll('.option.correct').length,1);assert.ok([...h.d.querySelectorAll('.option')].every(o=>o.disabled));assert.equal(h.d.querySelector('.question-card').dataset.corrected,'true');});
 h.d.querySelector('#learning').open=true;await delay();test('help after correction cannot reclassify original response',()=>assert.deepEqual(h.state().cycles[c.id].records[q.id].firstAttempt,first));h.click('[data-action=next]');const q2=c.questions[1];h.d.querySelector('#learning').open=true;await delay();h.click(`[data-option="${q2.answerId}"]`);h.confidence('media');h.click('[data-action=grade]');test('help before response tracked, confidence enters notebook',()=>{const a=h.state().cycles[c.id].records[q2.id].firstAttempt;assert.equal(a.assisted,true);assert.equal(a.confidence,'media');assert.ok(M.notebook(bank,h.state()).some(x=>x.q.id===q2.id));});
 h.click('[data-action=next]');const q3=c.questions[2];h.click(`[data-option="${q3.options.find(o=>o.id!==q3.answerId).id}"]`);h.confidence();h.click('[data-action=grade]');h.input('#cause','leitura');h.input('#note','Atenção ao conector.');const originalWrong=h.state().cycles[c.id].records[q3.id].firstAttempt;h.click('[data-action=notebook]');h.click(`[data-action=review][data-qid="${q3.id}"]`);test('review starts without old gabarito or previous choice',()=>{assert.equal(h.d.querySelector('#feedback'),null);assert.equal(h.d.querySelector('.option[aria-checked=true]'),null);assert.equal(h.d.querySelectorAll('.option.correct,.option.wrong').length,0);});h.click(`[data-option="${q3.answerId}"]`);h.confidence();h.click('[data-action=grade]');test('review stored separately and does not fix first score',()=>{const r=h.state().cycles[c.id].records[q3.id];assert.deepEqual(r.firstAttempt,originalWrong);assert.equal(r.reviews.length,1);assert.equal(M.stats(c,h.state().cycles[c.id]).correct,2);});
 h.click('[data-action=tools]');h.click('[data-action=backup]');await delay();test('real backup payload downloadable and valid',()=>{assert.ok(h.downloads.length);});const payload=await h.downloads[0].text();test('download includes note, reviews, checkpoint and no foreign keys',()=>{const b=M.validate(JSON.parse(payload),bank);assert.equal(b.cycles[c.id].records[q3.id].reviews.length,1);assert.ok(!payload.includes('OFFICIAL-SENTINEL'));});
 let saved=h.state();h.close();h=await harness();const restore=h.d.querySelector('#restore-file');Object.defineProperty(restore,'files',{configurable:true,value:[{size:payload.length,text:async()=>payload}]});restore.dispatchEvent(new h.w.Event('change',{bubbles:true}));await delay();test('file import drives complete recovery through UI',()=>{assert.equal(h.state().cycles[c.id].records[q3.id].note,'Atenção ao conector.');assert.equal(h.state().cycles[c.id].records[q3.id].reviews.length,1);assert.ok(h.d.body.textContent.includes('Backup importado.'));});
 const before=h.w.localStorage.getItem(M.KEY);Object.defineProperty(restore,'files',{configurable:true,value:[{size:20,text:async()=>'{bad JSON'}]});restore.dispatchEvent(new h.w.Event('change',{bubbles:true}));await delay();test('invalid import leaves storage byte-for-byte intact',()=>assert.equal(h.w.localStorage.getItem(M.KEY),before));
 h.click('[data-action=home]');h.click('[data-action=start]');h.quota(true);h.input('#note','Texto protegido na memória se a gravação falhar.');test('storage failure shown and no false saved claim',()=>{assert.ok(!h.d.querySelector('#save-alert').hidden);assert.equal(h.d.querySelector('#save-status').textContent,'Alterações ainda não salvas');});h.click('[data-action=backup]');await delay();const emergency=JSON.parse(await h.downloads.at(-1).text());test('emergency backup preserves unsaved note',()=>assert.ok(Object.values(emergency.cycles[c.id].records).some(r=>r.note==='Texto protegido na memória se a gravação falhar.')));h.quota(false);h.click('[data-action=retry]');test('retry persists actual in-memory state',()=>assert.ok(Object.values(h.state().cycles[c.id].records).some(r=>r.note==='Texto protegido na memória se a gravação falhar.')));h.close();
 // Complete real UI path on a fresh synthetic profile: both 70-question cycles.
 h=await harness();h.click('[data-action=start]');for(const cy of bank.cycles){for(const qq of cy.questions){assert.equal(h.d.querySelectorAll('.option').length,5);h.click(`[data-option="${qq.answerId}"]`);h.confidence('alta');h.click('[data-action=grade]');assert.ok(h.d.querySelector('#feedback').textContent.includes(qq.explanation));assert.equal(h.d.querySelectorAll('.alternative-reason').length,5);h.click('[data-action=next]');}h.click('[data-action=finish]');test(cy.id+' completed through all 70 visible question actions',()=>{assert.ok(h.state().cycles[cy.id].completedAt);assert.equal(M.stats(cy,h.state().cycles[cy.id]).points,115);});if(cy.id==='ciclo-01')h.click('[data-action=start][data-cycle=ciclo-02]');}
 test('after second cycle no fictional third cycle',()=>{assert.ok(h.d.body.textContent.includes('Os dois ciclos disponíveis terminam aqui.'));assert.equal(h.d.querySelector('[data-action=start]'),null);assert.equal(h.w.localStorage.getItem('dataprev_sessoes_states_v2'),'OFFICIAL-SENTINEL');assert.equal(h.w.localStorage.getItem('dataprev_sessoes_sync_queue_v2'),'QUEUE-SENTINEL');assert.deepEqual(h.errors,[]);});
 h.close();h=await harness('{"unexpected":true}');test('corrupt preexisting local record is not overwritten',()=>{assert.equal(h.w.localStorage.getItem(M.KEY),'{"unexpected":true}');assert.ok(!h.d.querySelector('#save-alert').hidden);});h.close();
 // Publishable visual fixtures contain only synthetic DOM and no learner data or scripts.
 h=await harness();let snapshots=[{name:'Início · 390px',width:390,html:h.d.documentElement.outerHTML}];h.click('[data-action=start]');snapshots.push({name:'Questão · 390px',width:390,html:h.d.documentElement.outerHTML});h.d.querySelector('#learning').open=true;await delay();snapshots.push({name:'Explicação · 390px',width:390,html:h.d.documentElement.outerHTML});snapshots.push({name:'Questão e explicação · 1024px',width:1024,html:h.d.documentElement.outerHTML});
 const escape=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');let fixture='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Ciclos · inspeção visual</title><style>body{font-family:system-ui;background:#e1e5e5;padding:20px;margin:0}section{margin-bottom:36px}iframe{display:block;border:1px solid #bcc9cf;background:white;height:1050px}h1{font-size:24px}h2{font-size:17px}</style></head><body><h1>Inspeção visual · dados sintéticos</h1><p>As telas abaixo usam o HTML gerado pelo aplicativo e o mesmo CSS, sem scripts ou gravação.</p>';
 for(const s of snapshots){let markup=s.html.replace(/<script[\s\S]*?<\/script>/g,'').replace('<head>','<head><base href="../">');fixture+=`<section><h2>${s.name}</h2><iframe title="${s.name}" width="${s.width}" sandbox="allow-same-origin" srcdoc="${escape(markup)}"></iframe></section>`;}
 fs.writeFileSync(path.join(__dirname,'visual-fixture.html'),fixture+'</body></html>');h.close();
 const result={status:'PASS',checks:results.length,tests:results,scope:'Isolated jsdom runtime and model tests, including 140-question UI completion, not Safari hardware certification.'};fs.writeFileSync(path.join(__dirname,'runtime-result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
