const {JSDOM}=require('jsdom');
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'https://qa.invalid/dataprev-sessoes/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,ctx=dom.getInternalVMContext(),checks=[],errors=[];
w.console.warn=(...a)=>errors.push(a.map(String).join(' '));w.console.error=w.console.warn;
w.setInterval=()=>0;w.setTimeout=()=>0;w.requestAnimationFrame=()=>0;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.matchMedia=()=>({matches:false});w.CSS={escape:s=>s};w.alert=s=>{throw Error('Unexpected alert: '+s)};w.confirm=()=>false;
w.fetch=async u=>{const p=new URL(u,w.location.href);assert.equal(p.origin,'https://qa.invalid','external read/write denied');const file=path.join(root,p.pathname.replace('/dataprev-sessoes/',''));return {ok:fs.existsSync(file),status:fs.existsSync(file)?200:404,json:async()=>JSON.parse(fs.readFileSync(file,'utf8'))}};
for(const m of html.matchAll(/<script src="\.\/([^?\"]+)/g))vm.runInContext(fs.readFileSync(path.join(root,m[1]),'utf8'),ctx,{filename:m[1]});
const run=code=>vm.runInContext(code,ctx),check=(name,fn)=>{fn();checks.push({name,status:'PASS'})};
const capture=[];
function visual(label){
 const body=w.document.body.cloneNode(true);body.querySelectorAll('script,.hidden').forEach(x=>x.remove());
 const view=w.document.body.dataset.view;
 if(view!=='trail')body.querySelector('#homePanel')?.remove();
 if(view!=='today')body.querySelector('#studyFocus')?.remove();
 if(view!=='lesson')body.querySelector('#sessionStats')?.remove();
 const css=[...w.document.querySelectorAll('style,link[rel=stylesheet]')].map(el=>el.tagName==='STYLE'?el.textContent:fs.readFileSync(path.join(root,el.getAttribute('href').replace('./','').split('?')[0]),'utf8')).join('\n')+'\n'+fs.readFileSync(path.join(root,'experience.css'),'utf8');
 fs.writeFileSync(path.join(root,'architecture/learning/experience-visual-styles-0.8.0.css'),css);
 capture.push({label,html:'<!doctype html><html lang="pt-BR"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="experience-visual-styles-0.8.0.css"></head>'+body.outerHTML+'</html>'});
}
(async()=>{
 for(let i=0;i<30;i++)await Promise.resolve();
 const baseline=w.localStorage.getItem('dataprev_sessoes_states_v2');
 check('Navigation among study trail and settings does not create learner evidence',()=>{for(const v of ['settings','trail','today'])w.DPExperience.navigate(v);assert.equal(w.localStorage.getItem('dataprev_sessoes_states_v2'),baseline);assert.equal(run('dpQueueCount()'),0);assert.equal(w.document.body.dataset.view,'today')});visual('Estudar — próxima ação e revisão');
 w.DPExperience.navigate('trail');
 check('Available filter hides unpublished sessions and preserves Python order',()=>{const ids=[...w.document.querySelectorAll('[data-discipline="Python e Ferramentas"] [data-road-id]')].filter(x=>!x.hidden).map(x=>x.dataset.roadId);assert(ids.indexOf('PY-LOOP-001')<ids.indexOf('PY-FUNC-001'));assert(ids.indexOf('PY-FUNC-001')<ids.indexOf('NP-001'));assert(w.document.querySelector('[data-road-id="EST-PROB-002"]').hidden)});
 const input=w.document.getElementById('trailSearch');input.value='variaveis';input.dispatchEvent(new w.Event('input'));
 check('Search normalizes accents and opens relevant results with accessible expansion',()=>{assert(!w.document.querySelector('[data-road-id="EST-VA-001"]').hidden);assert.equal(w.document.querySelector('[data-discipline="Estatística"] button').getAttribute('aria-expanded'),'true');assert(w.document.querySelector('[data-road-id="PY-FUNC-001"]').hidden)});visual('Trilha — busca por assunto');
 check('Empty search gives useful recovery without losing stored study',()=>{input.value='zzzzmissing';input.dispatchEvent(new w.Event('input'));assert.match(w.document.getElementById('trailResult').textContent,/Nenhuma sessão/);assert.equal(w.localStorage.getItem('dataprev_sessoes_states_v2'),baseline)});
 run("openSession('PY-LOOP-001')");
 check('Lesson outline prevents skipping practice and replaces duplicate navigation',()=>{assert.equal(w.document.querySelectorAll('.lesson-tools').length,1);assert.equal(w.document.querySelectorAll('.session-page-nav').length,0);assert(w.document.querySelector('[data-lesson-concept="1"]').disabled);assert(w.document.getElementById('nextConcept').disabled)});visual('Aula — leitura, exemplo e prática');
 run("state.notes[session.concepts[0].id]='rascunho preservado';saveState()");
 const stateObject=run('state'),sessionObject=run('session'),before=run('JSON.stringify(state)');
 check('Catalog update preserves exact active state, note and teaching object',()=>{run('applyCatalog({...catalog,sessions:[...catalog.sessions]})');assert.equal(run('state'),stateObject);assert.equal(run('session'),sessionObject);assert.equal(run('JSON.stringify(state)'),before)});
 const originalImmediate=run('JSON.stringify(state.immediate)');w.document.getElementById('adaptiveToggle').click();
 check('Help expands once within lesson and Escape returns focus without grading',()=>{w.document.getElementById('adaptiveToggle').click();assert.equal(w.document.querySelectorAll('.session-detail-overlay').length,1);assert(w.document.getElementById('studyBody').contains(w.document.querySelector('.session-detail-overlay')));assert.equal(w.document.querySelectorAll('[aria-modal=true]').length,0);assert.equal(run('JSON.stringify(state.immediate)'),originalImmediate)});visual('Ajuda — explicação dentro da aula');
 w.document.querySelector('.session-detail-overlay').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(w.document.activeElement.id,'adaptiveToggle');
 check('Invalid sync configuration cannot overwrite a valid saved configuration',()=>{run("saveConfig({endpoint:'https://qa.invalid/exec',token:'fixture',deviceId:'fixture'})");const key=run('SESSIONS_CFG_KEY'),saved=w.localStorage.getItem(key);for(const cfg of [{endpoint:'http://bad/exec',token:'x',deviceId:'x'},{endpoint:'https://qa.invalid/exec',token:'',deviceId:'x'},{endpoint:'invalid'}])assert.throws(()=>run('saveConfig('+JSON.stringify(cfg)+')'));assert.equal(w.localStorage.getItem(key),saved);w.localStorage.removeItem(key)});
 run("state.phase='final';renderFinal()");
 check('Final question has previous navigation, labelled confidence and no answer leakage',()=>{assert(w.document.getElementById('prevFinal'));assert.equal(w.document.querySelector('#studyBody .confidence').getAttribute('aria-label'),'Sua segurança na resposta');assert.equal(w.document.querySelectorAll('#studyBody .feedback,#studyBody .correct,#studyBody .wrong').length,0)});visual('Questão final — resposta e raciocínio');
 const sim=run("simCatalog.simulados.find(x=>simStatus(x)==='ready')");assert(sim);
 await run(`simOpen('${sim.id}')`);
 check('Opening exam pauses lesson and starts exam timer',()=>{assert.equal(run('state.timerRunning'),false);assert.equal(run('simState.timerRunning'),true)});
 const examId=run('simCurrent.id');w.DPExperience.navigate('today');
 check('Leaving exam saves paused state and returning resumes active clock',()=>{assert.equal(run('simState'),null);assert.equal(run(`simGetState('${examId}').timerRunning`),false)});
 await run(`simOpen('${examId}')`);assert.equal(run('simState.timerRunning'),true);
 run('simState.answers={};simState.answers[simCurrent.questions[0].id]={selected:simCurrent.questions[0].answer,confirmed:false};simState.answers[simCurrent.questions[1].id]={selected:simCurrent.questions[1].answer,confirmed:true};simRenderResult()');
 check('Exam result excludes correct but unconfirmed draft answers',()=>assert.equal(w.document.querySelector('.sim-result-stats .stat b').textContent,'1/70'));
 check('Gated exam cannot initiate mobile content generation',()=>{run("jsonp=()=>{throw Error('Forbidden generation')};simMaybeTriggerNext(simCatalog.simulados[1])")});
 w.DPExperience.navigate('settings');run("setStatus('Erro de teste recuperável','bad')");
 check('Operational failures are announced outside collapsed settings',()=>{assert.equal(w.document.getElementById('appNotice').getAttribute('role'),'alert');assert.match(w.document.getElementById('appNotice').textContent,/recuperável/)});
 assert.equal(errors.length,0,errors.join('\n'));
 const e=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
 fs.writeFileSync(path.join(root,'architecture/learning/experience-visual-0.8.0.html'),'<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>DATAPREV 0.8.0 — interface QA</title><style>body{font:16px system-ui;background:#e4e7eb;padding:20px}iframe{display:block;height:1300px;border:1px solid #ccc;max-width:100%;margin-bottom:30px}</style><h1>Interface 0.8.0 — dados fictícios</h1><p>DOM real dos componentes, sem scripts, sincronização ou dados do aluno.</p>'+capture.map((f,i)=>`<h2>${f.label}</h2><iframe id="mobile-${i}" title="${f.label} mobile" width="390" sandbox srcdoc="${e(f.html)}"></iframe><iframe id="desktop-${i}" title="${f.label} desktop" width="1024" sandbox srcdoc="${e(f.html)}"></iframe>`).join('')+'</html>');
 fs.writeFileSync(path.join(root,'architecture/runtime/experience-qa-0.8.0.json'),JSON.stringify({ok:true,checks,externalLearnerWrites:0,environment:'jsdom synthetic fixtures; physical iPhone not exercised'},null,2));
 console.log(JSON.stringify({ok:true,checks},null,2));process.exit(0);
})().catch(e=>{console.error(e);process.exit(1)});
